#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
sent=0

while [ $sent -le 9 ]
do
    echo "Best School"
    if [[ "$sent" == 8 ]]; then
        echo "Hi"
    fi
    ((sent++))
done
