#!/usr/bin/env bash
# displays information about the holbertonschool file.

FILE="holbertonschool"

if [ -e "$FILE" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "$FILE" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school  file does not exist"
fi
